### PR TITLE
Foundation

### PR DESCRIPTION
**Pull request by lschatzkin**

### CODE REVIEW

**Comment by wioux** [comment]
* `.each_slice(n)` is more idiomatic than `.in_groups_of(n, false)`
  * Similarly, prefer `row.each do |topic|` to `for topic in row`
  * Remove the new `<%= javascript_include_tag "application" %>` at the bottom of the template. Because of [turbolinks](https://github.com/turbolinks/turbolinks) it's actually more performant overall to have it in the `<head>` in our case.

Otherwise looks good. I'm interested to see how foundation compares to susy.

**Comment by wioux** [comment]
Let's also kill style rules that are no longer needed (`.row aside`, `.center`).

**Comment by wioux** [comment]
I'm doing some work on the `home#index` page, going to merge this to preempt conflicts. Can handle the notes in a follow up.

**Comment by lschatzkin** [comment]
Okay, my apologies for not getting to this yet, I got sidetracked...

**Pull request merged**
